### ISSUE TITLE
issues creating accounts and signing up

### ISSUE THREAD

**Issue by playhousehosting** [lifeitech/beenote#3]
Hello, 

I really think this project is amazing and can wait to use it. I have created a fork of this project and deployed it via Vercel but I am unable to sign up or log in. Could you point me in the right direction? I have also made an account on the site you are hosting but I am also unable to sign in there after creating an account and when I choose to reset my password I receive a 404 error. 

Thanks in advance,

**Comment by 3ffe** [comment]
Hi,

Thank you for your interest. This app uses [PocketBase](https://pocketbase.io/) as the backend for database storage and user authentication. If you want to deploy a copy, it is not enough to only deploy the website on Vercel. You also need to deploy your own PocketBase service on some server, and configure your backend server address through the environment variable in your Vercel dashboard (Note the `process.env.NEXT_PUBLIC_POCKETBASE` variable in the code. This variable will be replaced by your configured value during build).

Note how PocketBase JDK is used throughout the code to communicate with the backend and perform CRUD operations. Your deployed app will not run correctly, unless you use the exact same database schema. However, exposing the entire database schema to the public would post security risks, so I decide not to do so.

I would not suggest replicating the app. Rather, I hope people could see how Next.js 13 and PocketBase can work together and how to integrate OpenAI's API in Next.js, take inspirations from there and build their own apps.
